version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5499:5432"
    environment:
      - POSTGRES_USERNAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=docker-api-back